# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = {
    "client" =>  "172.16.2.10",
    "master1" => "172.16.2.11",
    "master2" => "172.16.2.12",
    "master3" => "172.16.2.13",
    "worker1" => "172.16.2.21",
    "worker2" => "172.16.2.22"
}

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  servers.each do |server_name, server_ip|
    config.vm.define server_name do |server_config|
      server_config.vm.hostname = "#{server_name}"
      server_config.vm.network "private_network", ip: server_ip
      server_config.vm.provider "virtualbox" do |vb|
        vb.name = server_name
        vb.memory = "4096"
        vb.cpus = 4
      end
    end
  end
end