# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "generic/centos7"
    master.vm.provider "virtualbox"
    master.vm.network "private_network", ip: "10.10.0.10"
    master.vm.synced_folder "/home/iuxt/code/nutstore-system-deployment/configuration/puppet/modules", "/etc/puppetlabs/code/modules",create: true,owner: "root", group: "root",mount_options:["dmode=775","fmode=644"]
    master.vm.synced_folder "/home/iuxt/code/nutstore-system-deployment/configuration/puppet/environments/production/manifests", "/etc/puppetlabs/code/environments/production/manifests",create: true,owner: "root", group: "root",mount_options:["dmode=775","fmode=644"]
    master.vm.hostname = "puppet-master"
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = "2"
    end
    master.vm.provision "shell", inline: <<-SHELL
       sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
       yum install puppetserver -y
       echo "127.0.0.1 puppet" >> /etc/hosts
    SHELL
  end

  config.vm.define "agent" do |agent|
    agent.vm.box = "generic/centos7"
    agent.vm.provider "virtualbox"
    agent.vm.network "private_network", ip: "10.10.0.11"
    agent.vm.hostname = "puppet-agent"
    agent.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = "2"
    end
    agent.vm.provision "shell", inline: <<-SHELL
       sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
       yum install puppet -y
       echo "10.0.0.10 puppet" >> /etc/hosts
    SHELL
  end
end
