# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # vagrant plugin install vagrant-vbguest
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  config.vm.define "node" do |node|
    node.vm.box = "generic/centos7"
    node.vm.provider "virtualbox"
    node.vm.network "private_network", ip: "10.0.0.12", virtualbox__intnet: true
    node.vm.network "forwarded_port", guest: 389, host: 1389
    node.vm.synced_folder ".", "/vagrant"
    node.vm.hostname = "openldap"
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "1"
    end
    node.vm.provision "shell", inline: <<-SHELL
        yum install openldap openldap-clients openldap-servers -y
        cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
        chown ldap. /var/lib/ldap/DB_CONFIG
        systemctl enable --now slapd

        passwd="{SSHA}nLyOWsRyvfvC6zRBL7M2ltlutgrIgnHH"
        echo $passwd

        cd /vagrant

        # set admin password
        ldapadd -Y EXTERNAL -H ldapi:/// -f chrootpw.ldif

        # Import basic Schemas.
        ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
        ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
        ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

        # generate directory manager's password
        ldapmodify -Y EXTERNAL -H ldapi:/// -f chdomain.ldif
        ldapadd -x -D cn=Manager,dc=nutstore,dc=com -w com.012 -f basedomain.ldif
        ldapadd -x -D cn=Manager,dc=nutstore,dc=com -w com.012 -f add_user.ldif

        systemctl stop firewalld
        systemctl disable firewalld
    SHELL
  end

end
