# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # vagrant plugin install vagrant-vbguest
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  config.vm.define "node" do |node|
    node.vm.box = "generic/centos7"
    node.vm.provider "virtualbox"
    node.vm.network "private_network", ip: "10.0.0.13", virtualbox__intnet: true
    node.vm.network "forwarded_port", guest: 1812, host: 1812
    node.vm.network "forwarded_port", guest: 1833, host: 1833
    node.vm.network "forwarded_port", guest: 1645, host: 1645
    node.vm.synced_folder ".", "/vagrant"
    node.vm.hostname = "radius"
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "1"
    end
    node.vm.provision "shell", inline: <<-SHELL
      yum install -y freeradius freeradius-utils freeradius-ldap
      /bin/cp -rf /vagrant/raddb/* /etc/raddb/
      systemctl restart radiusd
    SHELL
  end
end
