# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # vagrant plugin install vagrant-vbguest
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  # vagrant plugin install vagrant-hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "agent" do |agent|
    agent.vm.box = "generic/centos6"
    agent.vm.provider "virtualbox"
    agent.vm.network "private_network", ip: "10.10.0.13", virtualbox__intnet: true
    agent.vm.hostname = "agent-centos6"
    agent.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = "2"
    end
    agent.vm.provision "shell", inline: <<-SHELL
       sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-6.noarch.rpm
       yum install puppet -y
       systemctl stop puppet
       if [ `grep puppet /etc/hosts | wc -l` -eq 0 ]; then echo "10.10.0.10 puppet" >> /etc/hosts ;fi
       
    SHELL
  end
end
