# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # vagrant plugin install vagrant-vbguest
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  # vagrant plugin install vagrant-hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "master" do |master|
    master.vm.box = "generic/centos7"
    master.vm.provider "virtualbox"
    master.vm.network "private_network", ip: "10.10.0.10", virtualbox__intnet: true
    master.vm.synced_folder "/home/iuxt/code/nutstore-system-deployment/configuration/puppet/modules", "/etc/puppetlabs/code/modules",create: true,owner: "root", group: "root", mount_options:["dmode=775","fmode=644"]
    master.vm.synced_folder "/home/iuxt/code/nutstore-system-deployment/configuration/puppet/environments/production/manifests", "/etc/puppetlabs/code/environments/production/manifests",owner: "root", group: "root", mount_options:["dmode=775","fmode=644"]
    master.vm.hostname = "puppet"
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = "2"
    end
    master.vm.provision "shell", inline: <<-SHELL
       sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
       yum install puppetserver -y
       systemctl enable --now puppetserver
       systemctl disable --now firewalld
    SHELL
  end

#  config.vm.define "agent" do |agent|
#    agent.vm.box = "generic/centos8"
#    agent.vm.provider "virtualbox"
#    agent.vm.network "private_network", ip: "10.10.0.11", virtualbox__intnet: true
#    agent.vm.hostname = "puppet-agent"
#    agent.vm.provider "virtualbox" do |vb|
#      vb.gui = false
#      vb.memory = "4096"
#      vb.cpus = "2"
#    end
#    agent.vm.provision "shell", inline: <<-SHELL
#       sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-8.noarch.rpm
#       yum install puppet -y
#       systemctl stop puppet
#    SHELL
#  end
end
